language: c


matrix:
  include:
    # works on Precise and Trusty
    - dist: trusty
      before_install:
        - sudo git clone https://github.com/srdja/Collections-C.git
        - cd Collections-C
        - mkdir build
        - cmake ..
        - make
        - sudo make install
        - cd ..
        - autoreconf -i
      script: ./configure && make && make check && make distcheck
