language: c


matrix:
  include:
    - dist: bionic
      before_install:
        - git clone https://github.com/rogerioacp/Collections-C.git
        - cd Collections-C
        - mkdir build
        - cd build
        - cmake ..
        - make
        - sudo make install && sudo ldconfig && export LD_LIBRARY_PATH="/usr/local/bin"
        - cd ../..
        - autoreconf -i
      script: ./configure && make 
