language: c


matrix:
  include:
    - dist: bionic
      before_install:
        - sudo apt-get install -y cpputest
        - git clone https://github.com/srdja/Collections-C.git
        - cd Collections-C
        - mkdir build
        - cd build
        - cmake ..
        - make
        - sudo make install
        - cd ../..
        - autoreconf -i
      script: ./configure && make && make check && make distcheck
